name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - pip
  - wradlib
  - arm_pyart
  - cartopy
  - matplotlib
  - cartopy
  - numpy
  - xarray
  - metpy
  - pip:
      - sphinx-pythia-theme
